name: Stop Fly.io App
on:
  schedule:
    - cron: '0 17 * * *' 

jobs:
  stop-app:
    runs-on: ubuntu-latest
    steps:
    - name: Install Flyctl
      run: curl -L https://fly.io/install.sh | sh
    - name: Login to Fly
      run: flyctl auth token --token ${{ secrets.FLY_API_TOKEN }}
    - name: Stop App
      run: flyctl scale count 0 -a  foosball-bot
