name: Start Fly.io App
on:
  schedule:
    - cron: '0 6 * * *'

jobs:
  start-app:
    runs-on: ubuntu-latest
    steps:
    - name: Install Flyctl
      run: curl -L https://fly.io/install.sh | sh
    - name: Login to Fly
      run: flyctl auth token --token ${{ secrets.FLY_API_TOKEN }}
    - name: Start App
      run: flyctl scale count 1 -a foosball-bot
