name: Stop Fly.io App
on:
  schedule:
    - cron: "0 18 * * *"

jobs:
  stop-app:
    runs-on: ubuntu-latest
    steps:
      - name: Install Flyctl
        run: curl -L https://fly.io/install.sh | sh
      - name: Login to Fly
        run: fly auth token --token ${{ secrets.FLY_API_TOKEN }}
      - name: Stop App
        run: fly scale count 0 -a foosball-bot
